server:
  port: 8080
  shutdownTimeMillis: 10
  secretKey: CjKDMhscFvjxdCchVNanWqaqjQnmXAgc
  env: local

database:
  postgres:
    host: postgres
    port: 5432
    username: postgres
    password: postgres
    database: postgres
    ssl: disable

featureFlag:
  enableMigrations: true

jwt:
  accessTokenExpiryHours: 1
  refreshTokenExpiryHours: 24
